### ISSUE TITLE
P7: Join Game (8)

### ISSUE THREAD

**Issue by sccaeleo** [sccaeleo/crazy8s_482#3]
Allow players to join games in order to play with others.

**Comment by jpformato** [comment]
Join game and leave game functionality made: 7a37f97fb4933cb0fcc8a4d2d010a35e889d9edd

**Comment by jpformato** [comment]
5fd7bb71334a08aba6cbf5cde93841adf9606781

**Comment by jpformato** [comment]
Test Cases: 99441b9746cb4c58a5f004540cee2a76d326c963
